- hosts: all
  vars_files:
        - vars/imageName
  tasks:
        - package:
                name: docker-ce
                state: present

        - file:
                path: /root/Desktop/ImagesD
                state: directory

        - copy:
                dest: /root/Desktop/ImagesD
                src: "/root/Desktop/Desktop/software/DockerImages/{{ Dname }}.tar"

                
        - docker_image:
                name: "{{ Dname }}"
                load_path: "/root/Desktop/ImagesD/{{ Dname }}.tar"
                state: present
                source: load

        - service: 
                name: docker
                state: started

