- hosts: all
  vars_files:
        - vars
  tasks:
        - package:
                name: docker-ce
                state: present

        - service: 
                name: docker
                state: started

