- hosts: all
  vars_files:
        - vars/Dname
        - vars/imageName
  tasks:
        - docker_container:
                name: "{{ Dname }}"
                state: present
                image: "{{ image_name }}"
                command: sleep infinity
                
        - docker_container:
                name: "{{ Dname }}"
                state: started
                image: "{{ image_name }}"
