- hosts: localhost
  vars_files:
        - vars/ec2_variables
  tasks:
        - aws_s3:
               aws_access_key: AKIA3SPWFNR66HWNTB64
               aws_secret_key: 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
               bucket: akansha1
               object: /my/file
               src: /root/s3_put.yml
               mode: put
